### ISSUE TITLE
url parser issue

### ISSUE THREAD

**Issue by unknownuser88** [fcannizzaro/sublime-file-downloader#1]
Hi, nice plugin but I have some issues with some urls (see screenshot) it try to open https://cdnjs.cloudflare.com/ajax/libs/underscore.js/

![image](https://user-images.githubusercontent.com/2427559/33930739-5d03818e-e007-11e7-8731-bce0c6f91508.png)

**Comment by fcannizzaro** [comment]
check [1.0.2](https://github.com/fcannizzaro/sublime-file-downloader/releases/tag/1.0.2)
